<?php

namespace app\models;

/**
 * This is the model class for table "{{%tickets}}".
 *
 * @property int $id
 * @property int $offer_id
 * @property string $order_id
 * @property double $order_sum
 * @property string $comment
 * @property string $clicks
 *
 * @property Offers $offer
 */
class Tickets extends \yii\db\ActiveRecord
{
    protected $clicksArray;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%tickets}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['offer_id', 'order_id', 'order_sum'], 'required'],
            [['offer_id'], 'integer'],
            [['order_id', 'comment', 'clicks', 'order_sum'], 'string'],
//            [['order_sum'], 'number'],
            [['offer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Offers::className(), 'targetAttribute' => ['offer_id' => 'id']],
            [['clicksArray'], 'safe'] //TODO: Добавить валидатор на проверку is_array и count > 0
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'offer_id' => 'Offer ID',
            'order_id' => 'Order ID',
            'order_sum' => 'Order Sum',
            'comment' => 'Comment',
            'clicks' => 'Clicks',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffer()
    {
        return $this->hasOne(Offers::className(), ['id' => 'offer_id']);
    }

    public function beforeSave($insert)
    {
        if (!is_array($this->clicksArray) || !count($this->clicksArray)) {
            $this->addError('clicksArray', 'Должен быть выбран хотя бы один Checkbox');
            return false;
        }

        $this->clicks = serialize($this->clicksArray);
        if (!$this->validate()) {
            //TODO: Сообщение об ошибке
            return false;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
